### ISSUE TITLE
[Cop Request] MissingSignature

### ISSUE THREAD

**Issue by aaronmallen** [ksss/rubocop-on-rbs#75]
It would be awesome to have a cop that raises on missing signatures. Suggested default configuration:

```yaml
RBS/MissingSignature:
  Attributes:
    Enabled: true
  Constants:
    Enabled: true
  InstanceVariables:
    Enabled: false
  PublicMethods:
    Enabled: true
  ProtectedMethods:
    Enabled: true
  PrivateMethods:
    Enabled: false
```
